# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("Cristea's Calc"))
        MainWindow.resize(380, 370)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lcd = QtGui.QLCDNumber(self.centralwidget)
        self.lcd.setMinimumSize(QtCore.QSize(358, 87))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcd.setFont(font)
        self.lcd.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcd.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd.setDigitCount(8)
        self.lcd.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd.setObjectName(_fromUtf8("lcd"))
        self.verticalLayout.addWidget(self.lcd)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.plus = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.plus.setFont(font)
        self.plus.setAutoFillBackground(False)
        self.plus.setAutoDefault(False)
        self.plus.setDefault(False)
        self.plus.setFlat(False)
        self.plus.setObjectName(_fromUtf8("plus"))
        self.gridLayout_2.addWidget(self.plus, 0, 3, 1, 1)
        self.b4 = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setAutoFillBackground(False)
        self.b4.setAutoDefault(False)
        self.b4.setDefault(False)
        self.b4.setFlat(False)
        self.b4.setObjectName(_fromUtf8("b4"))
        self.gridLayout_2.addWidget(self.b4, 2, 0, 1, 1)
        self.b5 = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.b5.setFont(font)
        self.b5.setAutoFillBackground(False)
        self.b5.setAutoDefault(False)
        self.b5.setDefault(False)
        self.b5.setFlat(False)
        self.b5.setObjectName(_fromUtf8("b5"))
        self.gridLayout_2.addWidget(self.b5, 2, 1, 1, 1)
        self.minus = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.minus.setFont(font)
        self.minus.setAutoFillBackground(False)
        self.minus.setAutoDefault(False)
        self.minus.setDefault(False)
        self.minus.setFlat(False)
        self.minus.setObjectName(_fromUtf8("minus"))
        self.gridLayout_2.addWidget(self.minus, 2, 3, 1, 1)
        self.divide = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.divide.setFont(font)
        self.divide.setAutoFillBackground(False)
        self.divide.setObjectName(_fromUtf8("divide"))
        self.gridLayout_2.addWidget(self.divide, 4, 3, 1, 1)
        self.multiply = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.multiply.setFont(font)
        self.multiply.setAutoFillBackground(False)
        self.multiply.setObjectName(_fromUtf8("multiply"))
        self.gridLayout_2.addWidget(self.multiply, 3, 3, 1, 1)
        self.b7 = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.b7.setFont(font)
        self.b7.setAutoFillBackground(False)
        self.b7.setAutoDefault(False)
        self.b7.setDefault(False)
        self.b7.setFlat(False)
        self.b7.setObjectName(_fromUtf8("b7"))
        self.gridLayout_2.addWidget(self.b7, 0, 0, 1, 1)
        self.b0 = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.b0.setFont(font)
        self.b0.setAutoFillBackground(False)
        self.b0.setAutoDefault(False)
        self.b0.setDefault(False)
        self.b0.setFlat(False)
        self.b0.setObjectName(_fromUtf8("b0"))
        self.gridLayout_2.addWidget(self.b0, 4, 0, 1, 1)
        self.enter = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.enter.setFont(font)
        self.enter.setAutoFillBackground(False)
        self.enter.setAutoDefault(False)
        self.enter.setDefault(False)
        self.enter.setFlat(False)
        self.enter.setObjectName(_fromUtf8("enter"))
        self.gridLayout_2.addWidget(self.enter, 5, 3, 1, 1)
        self.b8 = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.b8.setFont(font)
        self.b8.setAutoFillBackground(False)
        self.b8.setAutoDefault(False)
        self.b8.setDefault(False)
        self.b8.setFlat(False)
        self.b8.setObjectName(_fromUtf8("b8"))
        self.gridLayout_2.addWidget(self.b8, 0, 1, 1, 1)
        self.b2 = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setAutoFillBackground(False)
        self.b2.setAutoDefault(False)
        self.b2.setDefault(False)
        self.b2.setFlat(False)
        self.b2.setObjectName(_fromUtf8("b2"))
        self.gridLayout_2.addWidget(self.b2, 3, 1, 1, 1)
        self.b1 = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setAutoFillBackground(False)
        self.b1.setAutoDefault(False)
        self.b1.setDefault(False)
        self.b1.setFlat(False)
        self.b1.setObjectName(_fromUtf8("b1"))
        self.gridLayout_2.addWidget(self.b1, 3, 0, 1, 1)
        self.period = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.period.setFont(font)
        self.period.setAutoFillBackground(False)
        self.period.setAutoDefault(False)
        self.period.setDefault(False)
        self.period.setFlat(False)
        self.period.setObjectName(_fromUtf8("period"))
        self.gridLayout_2.addWidget(self.period, 4, 1, 1, 1)
        self.b9 = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.b9.setFont(font)
        self.b9.setAutoFillBackground(False)
        self.b9.setAutoDefault(False)
        self.b9.setDefault(False)
        self.b9.setFlat(False)
        self.b9.setObjectName(_fromUtf8("b9"))
        self.gridLayout_2.addWidget(self.b9, 0, 2, 1, 1)
        self.b6 = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.b6.setFont(font)
        self.b6.setAutoFillBackground(False)
        self.b6.setAutoDefault(False)
        self.b6.setDefault(False)
        self.b6.setFlat(False)
        self.b6.setObjectName(_fromUtf8("b6"))
        self.gridLayout_2.addWidget(self.b6, 2, 2, 1, 1)
        self.b3 = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setAutoFillBackground(False)
        self.b3.setAutoDefault(False)
        self.b3.setDefault(False)
        self.b3.setFlat(False)
        self.b3.setObjectName(_fromUtf8("b3"))
        self.gridLayout_2.addWidget(self.b3, 3, 2, 1, 1)
        self.clr = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clr.sizePolicy().hasHeightForWidth())
        self.clr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.clr.setFont(font)
        self.clr.setAutoFillBackground(False)
        self.clr.setObjectName(_fromUtf8("clr"))
        self.gridLayout_2.addWidget(self.clr, 5, 2, 1, 1)
        self.plmin = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plmin.sizePolicy().hasHeightForWidth())
        self.plmin.setSizePolicy(sizePolicy)
        self.plmin.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.plmin.setFont(font)
        self.plmin.setObjectName(_fromUtf8("plmin"))
        self.gridLayout_2.addWidget(self.plmin, 4, 2, 1, 1)
        self.pow = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pow.sizePolicy().hasHeightForWidth())
        self.pow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pow.setFont(font)
        self.pow.setObjectName(_fromUtf8("pow"))
        self.gridLayout_2.addWidget(self.pow, 5, 1, 1, 1)
        self.sqrt = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sqrt.sizePolicy().hasHeightForWidth())
        self.sqrt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.sqrt.setFont(font)
        self.sqrt.setObjectName(_fromUtf8("sqrt"))
        self.gridLayout_2.addWidget(self.sqrt, 5, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Cristea's Calc", None))
        self.plus.setText(_translate("MainWindow", "+", None))
        self.plus.setShortcut(_translate("MainWindow", "+", None))
        self.b4.setText(_translate("MainWindow", "4", None))
        self.b4.setShortcut(_translate("MainWindow", "4", None))
        self.b5.setText(_translate("MainWindow", "5", None))
        self.b5.setShortcut(_translate("MainWindow", "5", None))
        self.minus.setText(_translate("MainWindow", "-", None))
        self.minus.setShortcut(_translate("MainWindow", "-", None))
        self.divide.setText(_translate("MainWindow", "/", None))
        self.divide.setShortcut(_translate("MainWindow", "/", None))
        self.multiply.setText(_translate("MainWindow", "*", None))
        self.multiply.setShortcut(_translate("MainWindow", "*", None))
        self.b7.setText(_translate("MainWindow", "7", None))
        self.b7.setShortcut(_translate("MainWindow", "7", None))
        self.b0.setText(_translate("MainWindow", "0", None))
        self.b0.setShortcut(_translate("MainWindow", "0", None))
        self.enter.setText(_translate("MainWindow", "Enter", None))
        self.enter.setShortcut(_translate("MainWindow", "Return", None))
        self.b8.setText(_translate("MainWindow", "8", None))
        self.b8.setShortcut(_translate("MainWindow", "8", None))
        self.b2.setText(_translate("MainWindow", "2", None))
        self.b2.setShortcut(_translate("MainWindow", "2", None))
        self.b1.setText(_translate("MainWindow", "1", None))
        self.b1.setShortcut(_translate("MainWindow", "1", None))
        self.period.setText(_translate("MainWindow", ".", None))
        self.period.setShortcut(_translate("MainWindow", ".", None))
        self.b9.setText(_translate("MainWindow", "9", None))
        self.b9.setShortcut(_translate("MainWindow", "9", None))
        self.b6.setText(_translate("MainWindow", "6", None))
        self.b6.setShortcut(_translate("MainWindow", "6", None))
        self.b3.setText(_translate("MainWindow", "3", None))
        self.b3.setShortcut(_translate("MainWindow", "3", None))
        self.clr.setText(_translate("MainWindow", "Clr", None))
        self.clr.setShortcut(_translate("MainWindow", "Backspace", None))
        self.plmin.setText(_translate("MainWindow", "+/-", None))
        self.pow.setText(_translate("MainWindow", "Pow", None))
        self.sqrt.setText(_translate("MainWindow", "Sqrt", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

